const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'..'),app=path.join(root,'game');
const project=JSON.parse(fs.readFileSync(path.join(app,'project.json')));
const cap=JSON.parse(fs.readFileSync(path.join(root,'capacitor.config.json')));
assert.equal(project.repository,'alanyen-git/yijie-luren');assert.equal(project.independent,true);
if(process.env.GITHUB_REPOSITORY)assert.equal(process.env.GITHUB_REPOSITORY,project.repository,'build must run in the independent repository');
assert.equal(cap.appId,'com.alanyen.yijieluren');assert.equal(cap.appName,'異界旅人');
assert.equal(fs.existsSync(path.join(root,'qunlu-app')),false);
assert.equal(fs.existsSync(path.join(app,'source-lock.json')),false);
const runtime=fs.readFileSync(path.join(app,'src/runtime.js'),'utf8'),keys=[];
const init=runtime.match(/function init\(\)\{[^\n]+/)[0];
const legacy={chronicle_save:'{"meta":{"game":"old"}}'};
const context={window:{localStorage:true},localStorage:{getItem:k=>{keys.push(k);return legacy[k]||null}},console,G:null};
vm.createContext(context);vm.runInContext(init+';init()',context);assert.deepEqual(keys,['yijie_luren_save']);assert.equal(context.G,null,'does not load another game save');
const slots=fs.readFileSync(path.join(app,'src/runtime-patches.js'),'utf8');assert.ok(slots.includes('yijie_luren_manual_slot_'));assert.ok(!slots.includes('qunlu_manual_slot_'));
const updater=fs.readFileSync(path.join(app,'src/apk-update.js'),'utf8');assert.ok(updater.includes('alanyen-git/yijie-luren/main/game/version.json'));assert.ok(!/dalu-game-web|qunlu-game/.test(updater));
const sw=fs.readFileSync(path.join(app,'sw.js'),'utf8');assert.ok(sw.includes('yijie-luren-pwa-'));assert.ok(sw.includes('key.startsWith(CACHE_PREFIX)'));
const build=fs.readFileSync(path.join(root,'scripts/prepare-web-game.cjs'),'utf8');assert.ok(!build.includes('getRegistrations()'));assert.ok(!build.includes('caches.delete('),'root navigation does not clear other games caches');
const meta=fs.readFileSync(path.join(app,'src/game-data.js'),'utf8');assert.ok(meta.startsWith('const DB={"meta":{"game_title":"異界旅人"'));
console.log('Project isolation passed: independent repo/app/source/update URLs, separate save/slot/cache keys, no cross-game cache clearing.');
