(function(){
"use strict";
function esc(v){return String(v==null?"":v).replace(/[&<>"]/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]})}
function marker(label,kind,onclick,meta){return '<button type="button" class="map-marker '+(kind||"")+'" onclick="'+onclick+'"><b>'+esc(label)+'</b>'+(meta?'<small>'+esc(meta)+'</small>':"")+'</button>'}
function shell(title,crumb,art,body){return '<div class="map-shell"><div class="map-toolbar"><div><p class="eyebrow">異界旅人・世界導覽</p><h3>'+esc(title)+'</h3></div><div class="map-level">'+crumb+'</div></div><div class="map-board '+art+'">'+body+'</div></div>'}
function goWorld(){openWorldMapHierarchy()}function goRealm(id){openRealmRegionMap(id)}function goProvince(id){openProvinceRegionMap(id)}
function facilityMarker(fid){var f=DB.facilities&&DB.facilities[fid];if(!f)return "";var names={guild:"冒險者公會",general:"商鋪",blacksmith:"鐵匠鋪",tavern:"酒館",inn:"旅館",church:"教會",clinic:"診療所",tailor:"裁縫鋪",alchemy:"煉金工坊",enchanter:"附魔工坊",mageguild:"魔法公會"};var label=names[fid]||f.name||fid;return marker(label,"facility","visitFacility('"+fid+"')",f.shop?"交易／服務":"對話／情報")}
function localBoard(l){var facilities=(l.facilities||[]).map(facilityMarker).join("");var links=(l.links||[]).map(function(x){var to=loc(x.to);return to?marker(to.name,"route","openMapLocationDetail('"+to.id+"')",x.hours+" 小時"):""}).join("");return '<div class="map-titleplate"><b>'+esc(l.name||"城鎮")+'</b><small>'+esc(l.size||"聚落")+'｜安全度 '+(l.safety_score==null?"—":l.safety_score)+'/100</small></div><div class="map-facilities">'+(facilities||"<span class='small'>此地尚未登錄設施。</span>")+'</div><div class="map-routes">'+links+'</div>'}
function settlementMap(){var c=mapHierarchyForLocation(),l=c.location;if(!l)return worldMap();var crumbs='<button onclick="goWorld()">世界</button>'+(c.realm?'<button onclick="goRealm(\''+c.realm.id+'\')">王國／政體</button>':"")+(c.province?'<button onclick="goProvince(\''+c.province.id+'\')">行省</button>':"");showModal(l.name+"・城鎮地圖",shell(l.name,crumbs,"settlement-map",localBoard(l)),"openMap()")}
function worldMap(){var maps=(DB.realm_region_maps||[]).map(function(r){var p=politicalEntity(r.political_entity_id);return marker(p?p.name:r.name,"realm-marker","goRealm(\''+r.id+'\')",(r.world_tier||(p&&p.world_tier)||"—")+"｜行省 "+((r.province_region_ids||[]).length))}).join("");showModal("世界地圖",shell("世界地圖","世界","world-map",'<div class="map-compass">N</div><div class="map-landmass"></div><div class="map-marker-layer">'+maps+'</div><div class="map-legend">點選王國／政體進入下一層；資料沿用群陸世界地圖。</div>'))}
function realmMap(id){var r=realmRegionMap(id);if(!r)return worldMap();var p=politicalEntity(r.political_entity_id);var maps=(r.province_region_ids||[]).map(function(pid){var x=provinceRegion(pid);return x?marker(x.name,"province-marker","goProvince(\''+x.id+'\')",(x.world_tier||"—")+"｜"+(x.administrative_type||"行省級區域")):""}).join("");showModal((p?p.name:r.name)+"・區域地圖",shell(p?p.name:r.name,'<button onclick="goWorld()">世界</button>',"realm-map",'<div class="map-compass">N</div><div class="map-landmass"></div><div class="map-marker-layer">'+(maps||"<span class='small'>此政體目前尚未展開行省級地圖。</span>")+'</div><div class="map-legend">'+esc(r.notes||"區域資料沿用群陸既有世界地圖。")+"</div>"),"goWorld()")}
function provinceMap(id){var p=provinceRegion(id);if(!p)return worldMap();var r=realmRegionMap(p.parent_realm_map_id);function rows(k,cl,label){return provinceCategoryLocations(p,k,false).slice(0,18).map(function(x){return marker(x.name,cl,"openMapLocationDetail(\''+x.id+'\')",(x.tier||"—")+"｜"+label)}).join("")}var maps=rows("town","town-marker","城鎮")+rows("wild","wild-marker","野外")+rows("dungeon","dungeon-marker","地下城");showModal(p.name+"・行省地圖",shell(p.display_name||p.name,'<button onclick="goWorld()">世界</button>'+(r?'<button onclick="goRealm(\''+r.id+'\')">王國／政體</button>':""),"province-map",'<div class="map-compass">N</div><div class="map-landmass"></div><div class="map-marker-layer">'+maps+'</div><div class="map-legend">城鎮、野外、地下城使用群陸既有節點與道路資料。</div>'),r?"goRealm('"+r.id+"')":"goWorld()")}
window.openMap=function(){var c=mapHierarchyForLocation();if(c.settlement&&c.location&&c.location.kind==="town")return settlementMap();if(c.province)return provinceMap(c.province.id);if(c.realm)return realmMap(c.realm.id);return worldMap()};
window.openWorldMapHierarchy=worldMap;window.openRealmRegionMap=realmMap;window.openProvinceRegionMap=provinceMap;
})();